### ISSUE TITLE
不知为何 GET /folder 总是返回503错误

### ISSUE THREAD

**Issue by xinxin8816** [Srar/189CloudLinkTools#5]
Auth绑定都是正常的，应该不是天翼API的问题
大佬知道这是什么问题吗
<img src="https://s1.ax1x.com/2018/04/10/CF73Ix.png" alt="CF73Ix.png" border="0" />

**Comment by Srar** [comment]
这个项目是我刚学Node时候的练手项目所以没有做详细错误输出。

你可以打开Chrome的开发者工具点击Network查看到底返回了什么错误。

**Comment by xinxin8816** [comment]
@Srar 多谢指教，具体错误如下
<img src="https://s1.ax1x.com/2018/04/10/CF70eA.png" alt="CF70eA.png" border="0" />

**Comment by Srar** [comment]
点击`folder`有个`Response`选项卡, 里面内容截图下？

**Comment by xinxin8816** [comment]
@Srar 错误如下
{"original":null,"response":{"req":{"method":"GET","url":"http://api.189.cn/ChinaTelecom/listFiles.action"},"header":{"server":"openresty","date":"Tue, 10 Apr 2018 11:26:35 GMT","content-type":"application/json; charset=UTF-8","connection":"close","content-language":"zh-CN"},"status":400,"text":"{\"res_code\":\"1\",\"res_message\":\"Unknown error,sessionkey is null.\"}\n"},"status":400}

**Comment by xinxin8816** [comment]
似乎和上个Issues一样的问题了

**Comment by Srar** [comment]
那不是很清楚啥原因 我翻下文档看看

**Comment by Srar** [comment]
文档里貌似没有写, 不妨询问下天翼开发平台的客服？

**Comment by xinxin8816** [comment]
好的，开发者社区已经名存实亡了，我去尝试一下邮件联系客服

**Comment by luoye663** [comment]
这个天翼云已经废了，除了以前的老帐号可以正常授权以外，新申请的key都是废的

**Comment by xinxin8816** [comment]
@anchsss 好吧，谢谢
